auth_user/api/urls.py
from django.urls import path
from .views import (
    register, profile, profileUpdate, ObtainAuthTokenView
)
from rest_framework.authtoken.views import obtain_auth_token


app_name='auth_user'

urlpatterns = [
    path('register', register, name='register'), 
    path('login', ObtainAuthTokenView.as_view(), name='login'),
    path('profile', profile, name='profile'), 
    path('profile/update', profileUpdate, name='profile_update'), 
]

blog/api/urls.py
from django.urls import path
from .views import (blogPostDetail, 
    blogPostDelete, 
    blogPostUpdate, 
    blogPostCreate,
    BlogPostList
)

app_name='blog'

urlpatterns = [
    path('', BlogPostList.as_view(), name='index'),
    path('create', blogPostCreate, name='create'),
    path('<slug>/', blogPostDetail, name='detail'),
    path('<slug>/update', blogPostUpdate, name='update'),
    path('<slug>/delete', blogPostDelete, name='delete'),
   
]

blog/urls.py
from django.urls import path, include
from .views import (create, detail, edit)

app_name='blog'

urlpatterns = [
    path('create', create, name='create'),
    path('<slug>', detail, name='detail'),
    path('<slug>/edit', edit, name='edit'),
]

rest_api/urls.py
from django.contrib import admin
from django.urls import path, include
from auth_user import views as authViews
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('blog/', include('blog.urls', 'blog')),
    path('register/', authViews.register, name='register'),
    path('logout/', authViews.signout, name='logout'),
    path('login/', authViews.signin, name='login'),
    path('must_authenticate/', authViews.mustAuth, name='must_auth'),
    path('profile/', authViews.profile, name='profile'),
    path('auth/password_change/', auth_views.PasswordChangeView.as_view(template_name='auth/password_change.html'), name='password_change'),
    path('auth/password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='auth/password_change_done.html'), name='password_change_done'),
    path('auth/password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('auth/password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='auth/password_reset_done.html'), name='password_reset_done'),
    path('auth/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('auth/reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='auth/password_reset_complete.html'), name='password_reset_complete'),

    # API
    path('api/blog/', include('blog.api.urls', 'blog_api')),
    path('api/auth/', include('auth_user.api.urls', 'auth_api')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.conf import settings
from django.db.models.signals import post_delete
from django.dispatch import receiver

def uploadLocation(instance, filename, **kwargs):
    filePath = 'blog/{author_id}/{title}-{filename}'.format(
        author_id = str(instance.author.id),
        title=str(instance.title),
        filename = filename 
    )

    return filePath

class BlogPost(models.Model):
    title = models.CharField(max_length=50, null=False, blank=True)
    body = models.TextField(max_length=5000, null=False, blank=True)
    image = models.ImageField(upload_to=uploadLocation, null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    slug = models.SlugField(blank=True, unique=True)

    def __str__(self):
        return self.title

@receiver(post_delete, sender=BlogPost)
def submissionDelete(sender, instance, **kwargs):
    instance.image.delete(False)

def preSaveBlogPostReceiver(sender, instance, **kwargs):
    instance.slug = slugify(instance.author.username+'-'+instance.title)

pre_save.connect(preSaveBlogPostReceiver, sender=BlogPost)

blog/forms.py
from django import forms
from django.forms import fields
from .models import BlogPost

class CreateBlogPostForm(forms.ModelForm):

    class Meta:
        model = BlogPost
        fields = ['title', 'body', 'image']

class UpdateBlogPostForm(forms.ModelForm):
    class Meta:
        model=BlogPost
        fields=['title', 'body', 'image']

    def save(self, commit=True):
        post = self.instance
        post.title = self.cleaned_data['title']
        post.body=self.cleaned_data['body']

        if self.cleaned_data['image']:
            post.image = self.cleaned_data['image']

        if commit:
            post.save()
        return post

auth_user/api/views.py
from django.http import request
from rest_framework import status
from rest_framework.response import Response
from rest_framework.authtoken.models import Token
from rest_framework.decorators import api_view, permission_classes, authentication_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.views import APIView
from django.contrib.auth import authenticate

from auth_user.models import AuthUser
from .serializers import RegistrationSerializer, ProfileSerializer

@authentication_classes([])
@permission_classes([])
@api_view(['POST'])
def register(request):

    serializer = RegistrationSerializer(data=request.data)

    if serializer.is_valid():
        user = serializer.save()
        
        return Response({
            'email':user.email,
            'username':user.username, 
            'token':Token.objects.get(user=user).key
        })
        
    return Response(serializer.errors)

@api_view(['GET'])
@permission_classes([IsAuthenticated])
def profile(request):
    try:
        user = request.user
    except AuthUser.DoesNotExist:
        return Response(status=HTTP_404_NOT_FOUND)
    
    serializer = ProfileSerializer(user)
    return Response(serializer.data)


@api_view(['PUT'])
@permission_classes([IsAuthenticated])
def profileUpdate(request):
    try:
        user = request.user
    except AuthUser.DoesNotExist:
        return Response(status=HTTP_404_NOT_FOUND)
    
    serializer = ProfileSerializer(user, data=request.data)

    if serializer.is_valid():
        serializer.save()
        
        return Response({'message':'Profile updated'})
    
    return Response({'message':'Failed'}, HTTP_400_BAD_REQUEST)


# Custom Login
class ObtainAuthTokenView(APIView):
    authentication_classes = []
    permission_classes = []

    def post(self, request):
        email = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(email=email, password=password)

        if user:
            try:
                token = Token.objects.get(user=user)
            except Token.DoesNotExist:
                token = Token.objects.create(user=user)
            context = {
                'message':'Login Success',
                'id':user.id,
                'email':user.email,
                'token':token.key
            }
            return Response(context)
        else:
            context = {
                'message':'Invalid credentials',
            }
        
        return Response(context, status=HTTP_404_NOT_FOUND)

blog/api/views.py
from auth_user.api.views import register
from django.http.response import HttpResponse
from django.views.decorators.http import require_http_methods
from django.shortcuts import render
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.pagination import PageNumberPagination
from rest_framework.generics import ListAPIView  
from rest_framework.authentication import TokenAuthentication
from rest_framework.filters import SearchFilter, OrderingFilter

from auth_user.models import AuthUser
from blog.models import BlogPost
from .serializers import BlogPostSerializer, BlogPostCreateSerializer, BlogPostUpdateSerializer
from blog.policies import canCreate, canDelete, canUpdate


class BlogPostList(ListAPIView):
    queryset = BlogPost.objects.all()
    serializer_class = BlogPostSerializer
    authentication_classes = [TokenAuthentication]
    permission_classes = [IsAuthenticated]
    pagination_class = PageNumberPagination
    search_fields = ['title', 'body', 'author__username']
    filter_backends = [SearchFilter,OrderingFilter]


@api_view(['GET'])
@permission_classes([IsAuthenticated])
def blogPostDetail(request, slug):
    try:
        post = BlogPost.objects.get(slug=slug)
    except BlogPost.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    serializer = BlogPostSerializer(post)
    return Response(serializer.data)

@api_view(['PUT'])
@permission_classes([IsAuthenticated])
def blogPostUpdate(request, slug):
    try:
        post = BlogPost.objects.get(slug=slug)

        if not canUpdate(request, post):
            return Response({'message':'Update forbidden'}, status=status.HTTP_403_FORBIDDEN)

    except BlogPost.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    serializer = BlogPostUpdateSerializer(post, data=request.data, partial=True)
    
    if serializer.is_valid():
        serializer.save()
        return Response(data={'message':'Update success'})

    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['DELETE'])
@permission_classes([IsAuthenticated])
def blogPostDelete(request, slug):
    try:
        post = BlogPost.objects.get(slug=slug)

        if not canDelete(request, post):
            return Response({'message':'Delete forbidden'}, status=status.HTTP_403_FORBIDDEN)
    except BlogPost.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if post.delete():
        return Response(data={'message':'Delete success'})
    else:
        return Response(data={'message':'Delete failed'}, status=status.HTTP_400_BAD_REQUEST)


@api_view(['POST'])
@permission_classes([IsAuthenticated])
def blogPostCreate(request):
    if not canCreate(request):
            return Response({'message':'Create forbidden'},status=status.HTTP_403_FORBIDDEN)

    data = request.data
    data['author'] = request.user.id

    serializer = BlogPostCreateSerializer(data=request.data)

    if serializer.is_valid():
        serializer.save()
        return Response(serializer.data, status=status.HTTP_201_CREATED)

    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

blog/views.py
from django.http.response import HttpResponse
from django.views.decorators.http import require_http_methods
from django.shortcuts import get_object_or_404, render, redirect
from .models import BlogPost
from .forms import CreateBlogPostForm, UpdateBlogPostForm
from auth_user.models import AuthUser
from auth_user.views import isAuth
from django.db.models import Q
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .policies import canUpdate, canCreate, canDelete

@require_http_methods(["GET", "POST"])
@login_required(login_url='/login', redirect_field_name='')
def create(request):

    if not canCreate(request):
        return redirect('home')

    form = CreateBlogPostForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        data = form.save(commit=False)
        author = AuthUser.objects.filter(email=request.user.email).first()
        data.author = author
        data.save()
        form = CreateBlogPostForm()
        messages.success(request, 'Post created successfully!')
        return redirect('blog:create')

    return render(request, 'blog/create.html', context={
        'form':form
    })


def detail(request,slug):
    context = {}

    post = get_object_or_404(BlogPost, slug=slug)

    return render(request, 'blog/detail.html', context={
        'post':post
    })


@require_http_methods(["GET", "POST"])
@login_required(login_url='/login', redirect_field_name='')
def edit(request,slug):
    # if not request.user.is_authenticated:
    #     return redirect('must_auth')

    post = get_object_or_404(BlogPost, slug=slug)

    if not canUpdate(request, post):
        return redirect('home')

    if request.POST:
        form = UpdateBlogPostForm(request.POST or None, request.FILES or None, instance=post)

        if form.is_valid():
            data = form.save(commit=False)
            data.save()

            post = data
            messages.success(request, 'Post updated successfully!')
            return redirect('blog:edit', post.slug)

    form = UpdateBlogPostForm(initial={
        'title':post.title,
        'body':post.body,
        'image':post.image,
    })

    return render(request, 'blog/edit.html', context={
        'form':form
    })


def getBlogQuerySet(query=None):
    queryset = BlogPost.objects
    queries = query.split(" ")
    for q in queries:
        queryset = queryset.filter(Q(title__icontains=q) | Q(body__icontains=q))
    
    queryset = queryset.distinct()

    return queryset

blog/templates/blog/api.html
{% extends "rest_framework/base.html" %}

blog/templates/blog/create.html
{% extends 'app.html' %}

{% block content %}

<h1>Add post</h1>

<div class="col-lg-7 offset-lg-1">
    <form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

        <!-- title -->
        <div class="form-group">
            <label for="id_title">Title</label>
            <input class="form-control" type="text" name="title" id="id_title" placeholder="Title" required autofocus>
        </div>

        <!-- Body -->
        <div class="form-group">
            <label for="id_body">Content</label>
            <textarea class="form-control" rows="10" type="text" name="body" id="id_body" placeholder="This blog is about..." required></textarea>
        </div>

        <!-- Image -->
        <div class="form-group">
            <label for="id_image">Image</label>
            <input  type="file" name="image" id="id_image" accept="image/*" required>
        </div>

        <!-- Submit btn -->
        <button class="submit-button btn btn-lg btn-primary btn-block" type="submit">POST</button>
    </form>	
</div>

{% endblock content %}

blog/templates/blog/detail.html
{% extends 'app.html' %}

{% block content %}

<div class="col-lg-7 offset-lg-1">
    <h1>{{post.title}}</h1>
    <img width="250px" height="200px" src="{{post.image.url}}" alt="">
    <p>{{post.body|safe}}</p>
    <small>{{post.updated_at}}</small>
</div>

<hr>

{% if request.user.is_authenticated and post.author == request.user %}
<a href="{% url 'blog:edit' post.slug %}">Edit</a>
{% endif %}

{% endblock content %}

blog/templates/blog/edit.html
{% extends 'app.html' %}

{% block content %}

<div class="col-lg-7 offset-lg-1">
    <form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

        <!-- title -->
        <div class="form-group">
            <label for="id_title">Title</label>
            <input class="form-control" type="text" name="title" id="id_title" placeholder="Title" value="{{form.initial.title}}" required autofocus>
        </div>

        <!-- Body -->
        <div class="form-group">
            <label for="id_body">Content</label>
            <textarea class="form-control" rows="10" type="text" name="body" id="id_body" placeholder="This blog is about..." 
            required>{{form.initial.body}}</textarea>
        </div>

        <!-- Image -->
        <div class="form-group image-group" id="id_image_group">
            <img class="img-fluid image" src="{{form.initial.image.url}}" id="id_image_display">
              <div class="middle">
                <div class="text">Change image</div>
              </div>
        </div>
        <input type="file" name="image" id="id_image_file" accept="image/*" onchange="readURL(this)">
        

        {% for field in form %}
            <p>
                {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                {% endfor %}
            </p>
        {% endfor %}
        {% if form.non_field_errors %}
            <div style="color: red">
                <p>{{form.non_field_errors}}</p>
            </div>
        {% endif %}

        <!-- Submit btn -->
        <button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Update</button>
    </form>	
</div>


<script type="text/javascript">
	document.getElementById('id_image_group').onclick = function(event){
    	document.getElementById('id_image_file').click();
    };

	function readURL(input){
		var reader = new FileReader();
		reader.onload = function (e) {
            $('#id_image_display')
                .attr('src', e.target.result)
        };
		reader.readAsDataURL(input.files[0]);
	}
</script>

{% endblock content %}